
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      testOnReturn: false
      testWhileIdle: true
      maxActive: 30
      removeAbandoned: true
      username: root
      name: datasource
      testOnBorrow: false
      minIdle: 10
      initialSize: 5
      poolPreparedStatements: true
      url: jdbc:mysql://10.20.8.15:3306/scms?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      type: com.alibaba.druid.pool.DruidDataSource
      validationQuery: select 1
      maxOpenPreparedStatements: 300
      password: '*A^S@.*3.HQAzNSA'
#      password:


server:
  servlet:
    context-path: /sys
  port: 9998

mybatis:
  mapper-locations: classpath:com/xy/commondb/mapper/*.xml,classpath:com/xy/sys/mapper/*.xml